spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://ec2-54-225-234-165.compute-1.amazonaws.com:5432/d8f8d15b7r95dl
#    username: isyjrokcrsvdoo
#    password: ecd8e5f171fd000ebfe38fb4fa35365b205425d8af0d254d965cb6432400db1a

#Test
  datasource:
      url: jdbc:mariadb://localhost:3306/football
      username: root
      password: 4316
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
#Test
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_ssql: true

#Test
#  config:
#    activate:
#      on-profile: prod

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace