spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-206-214-233.compute-1.amazonaws.com:5432/dqlob21lu4lm9
    username: modqrjbbyvlahz
    password: 75a999f2537a8005cf0e21116bf8fa20774e1626e20b5ff4643509a724d1242d

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_ssql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace